kind: Service
apiVersion: v1
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-boot-service
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30088
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-service
spec:
  selector:
      matchLabels:
        app: spring-boot-service
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-service
    spec:
      containers:
        - name: spring-boot-service
          image: mayurbhosure/docker:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf  
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf 
                  key: host
                  
